# Generated by Django 4.1.6 on 2023-04-12 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('price', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=99, null=True)),
                ('hash_of_json_file', models.CharField(blank=True, max_length=66, null=True)),
                ('hash_payment_receipt', models.CharField(blank=True, max_length=66, null=True)),
                ('participants', models.ManyToManyField(blank=True, default=None, related_name='participants', to='address.address')),
                ('winner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.address')),
            ],
        ),
    ]
