# Generated by Django 4.1.6 on 2023-04-12 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
        ('auction', '0002_auction_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='images',
        ),
        migrations.AddField(
            model_name='auction',
            name='images',
            field=models.ManyToManyField(blank=True, default=None, related_name='photos', to='image.image'),
        ),
    ]
